import * as Bootstrap from 'react-bootstrap';
import { Link } from 'react-router';
export declare const NavDropDown: typeof Bootstrap.NavDropdown;
export declare const FormControl: Bootstrap.FormControlClass;
export declare const InputGroup: Bootstrap.InputGroupClass;
export declare const FormGroup: typeof Bootstrap.FormGroup;
export declare const HelpBlock: typeof Bootstrap.HelpBlock;
export declare const MenuItem: typeof Bootstrap.MenuItem;
export declare const Collapse: typeof Bootstrap.Collapse;
export declare const NavItem: __React.ClassicComponentClass<Bootstrap.NavItemProps>;
export declare const Button: __React.ClassicComponentClass<Bootstrap.ButtonProps>;
export declare const Navbar: Bootstrap.NavbarClass;
export declare const Table: __React.ClassicComponentClass<Bootstrap.TableProps>;
export declare const Panel: __React.ClassicComponentClass<Bootstrap.PanelProps>;
export declare const Image: __React.ClassicComponentClass<Bootstrap.ImageProps>;
export declare const Form: typeof Bootstrap.Form;
export declare const Grid: __React.ClassicComponentClass<Bootstrap.GridProps>;
export declare const Well: typeof Bootstrap.Well;
export declare const Row: __React.ClassicComponentClass<Bootstrap.RowProps>;
export declare const Col: __React.ClassicComponentClass<Bootstrap.ColProps>;
export declare const Nav: typeof Bootstrap.Nav;
export declare const RouteLink: typeof Link;
